// #include<iostream>
// using namespace std;
// int main()
// {
//     int n;
//     cin>>n;
//     int level=1;
//     int sum=1;
//     for (int  i = 2; i <=n; i++)
//     {
//         level=level+1;
//         sum=sum+level;
//     }
//     cout << sum;
//     return 0;
// }

#include<iostream>

using namespace std;

int main()
{
    int n=0;
    cin >> n;
    double a[100]={0};
    double b[100]={0};

   
    return 0;
}

